Repository HospitalRun/components, pull requests merged in 2019-10, with the labels that each got.

#51 Docs update
  .github/CONTRIBUTING.md
  README.md
Labels: core-team, documentation

#53 Adds GitHub Action support
  .github/workflows/ci.yml
  README.md
  azure-pipeline.yml
  azure/azure-pipelines-npm.yml
  azure/azure-pipelines-yarn.yml
Labels: core-team, devops

#56 feat(text): adds text field component
  src/components/TextField/TextField.tsx
  src/components/TextField/index.tsx
  src/helpers/ControlSize.ts
  src/index.tsx
  stories/textfield.stories.tsx
  test/textfield.test.tsx
Labels: enhancement, good first issue

#71 ci(github): fixes github ci yaml
  .github/workflows/ci.yml
Labels: core-team, devops

#72 feat(alerts): adds Alert component
  .travis.yml
  package.json
  src/components/Alert/Alert.tsx
  src/components/Alert/index.tsx
  src/index.tsx
  stories/alerts.stories.tsx
  test/alert.test.tsx
  test/badge.test.tsx
  test/bargraph.test.tsx
  test/button.test.tsx
  test/icon.test.tsx
  test/linegraph.test.tsx
  test/piegraph.test.tsx
  test/pill.test.tsx
  test/spinner.test.tsx
  test/textfield.test.tsx
Labels: enhancement

#74 feat(textinput): adds TextInput component
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/index.tsx
  src/index.tsx
  stories/textinput.stories.tsx
  test/textinput.test.tsx
Labels: enhancement, good first issue

#73 feat(radios): adds radio component
  src/components/Radio/Radio.tsx
  src/components/Radio/index.tsx
  src/index.tsx
  stories/radio.stories.tsx
  test/radio.test.tsx
Labels: enhancement, good first issue

#68 feat(navbar): add Navbar component
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/index.tsx
  src/components/Navbar/interfaces.tsx
  src/index.tsx
  stories/navbar.stories.tsx
  test/navbar.test.tsx
Labels: enhancement

#70 feat(switch): add Switch component
  package.json
  src/components/Switch/Switch.tsx
  src/components/Switch/index.tsx
  src/index.tsx
  stories/switch.stories.tsx
  test/switch.test.tsx
Labels: enhancement

#67 feat(checkboxes): adds Checkbox component
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/index.tsx
  src/components/Radio/Radio.tsx
  src/index.tsx
  stories/checkbox.stories.tsx
  test/checkbox.test.tsx
Labels: enhancement

#82 feat(select): add Select component
  src/components/Select/Select.tsx
  src/components/Select/index.tsx
  src/index.tsx
  stories/select.stories.tsx
  test/select.test.tsx
Labels: enhancement, in progress

#83 feat(textinput): add placeholder for text input
  src/components/TextInput/TextInput.tsx
  stories/textinput.stories.tsx
  test/textinput.test.tsx
Labels: enhancement

#85 refactors components to use functional components where possible
  src/components/Badge/Badge.tsx
  src/components/Button/Button.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Icon/Icon.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Pill/Pill.tsx
  src/components/Radio/Radio.tsx
  src/components/Select/Select.tsx
  src/components/Spinner/Spinner.tsx
  src/components/Switch/Switch.tsx
  src/components/TextField/TextField.tsx
  src/components/TextInput/TextInput.tsx
  test/navbar.test.tsx
Labels: enhancement
