Repository HospitalRun/components, pull requests merged in 2019-09, with the labels that each got.

#5 adds support for line graphs, bar graphs, and pie graphs for basic graph components
  .gitignore
  package.json
  src/components/Graph/index.tsx
  src/components/Graph/interfaces.ts
  src/index.tsx
  stories/graphs.stories.tsx
  test/bargraph.test.tsx
  test/linegraph.test.tsx
  test/piegraph.test.tsx
  test/spinner.test.tsx
  test/toaster.test.tsx
Labels: enhancement

#12 documentation upgrades
  .github/CONTRIBUTING.md
  .storybook/config.js
  .storybook/webpack.config.js
  README.md
  buildDocs.sh
  docs/BarGraph.md
  docs/LineGraph.md
  docs/PieGraph.md
  docs/Spinner.md
  genDocs.sh
  generateMarkdown.js
  package.json
  src/components/Graph/BarGraph.tsx
  src/components/Graph/LineGraph.tsx
  src/components/Graph/PieGraph.tsx
  src/components/Graph/index.tsx
  src/components/Graph/util.ts
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/index.tsx
  stories/graphs.stories.tsx
  stories/spinner.stories.tsx
Labels: documentation, enhancement

#13 refactor: refactors tsconfig files
  stories/tsconfig.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.storybook.json
Labels: enhancement

#11 WIP: Tree Shaking of v0.1.2
  .storybook/config.js
  README.md
Labels: enhancement, in progress

#15 Adds Commitizen
  .gitignore
  .releaserc.js
  README.md
  commitlint.config.js
  package.json
Labels: enhancement, in progress

#18 :construction_worker: (travis) Adds coveralls support
  .travis.yml
  CHANGELOG.md
  README.md
  package.json
Labels: enhancement, in progress

#37 :green_heart: (release) Updates releaserc
  .releaserc.js
  package.json
Labels: bug

#40 ci(devops): improves azure pipeline ci
  azure-pipeline.yml
  build/azure-pipeline-npm.yml
  build/azure-pipelines-yarn.yml
Labels: devops, enhancement

#41 ci(devops): removes gitmoji deps
  .releaserc
  .releaserc.js
  commitlint.config.js
  package.json
Labels: core-team, devops

#44 adding prepublish command so the library will build before publish
  .travis.yml
  package.json
Labels: bug

#45 Enzyme testing
  package.json
  test-setup.ts
  test/bargraph.test.tsx
  test/linegraph.test.tsx
  test/piegraph.test.tsx
  test/spinner.test.tsx
Labels: core-team, enhancement

#48 fix(ci): changes to fix deprecation warning about prepublish
  package.json
Labels: bug, core-team

#46 Buttons
  package.json
  src/components/Button/Button.tsx
  src/components/Button/index.tsx
  src/components/Button/interfaces.ts
  src/components/Icon/Icon.tsx
  src/components/Icon/index.tsx
  src/components/Icon/interfaces.ts
  src/index.tsx
  stories/buttons.stories.tsx
  stories/icons.stories.tsx
  test/button.test.tsx
  test/icon.test.tsx
Labels: core-team, enhancement

#49 Typescript-eslint issues and storybook improvements
  package.json
  stories/confirm.stories.tsx
  stories/toaster.stories.tsx
Labels: bug, core-team, enhancement

#50 Badges
  src/components/Badge/Badge.tsx
  src/components/Badge/index.tsx
  src/components/Pill/Pill.tsx
  src/components/Pill/index.tsx
  src/index.tsx
  stories/badges.stories.tsx
  stories/buttons.stories.tsx
  stories/icons.stories.tsx
  stories/pills.stories.tsx
  test/badge.test.tsx
  test/pill.test.tsx
Labels: core-team, enhancement
