Repository HospitalRun/components, pull requests merged in 2019-12, with the labels that each got.

#136 fix(labels): fix missing label export
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/index.ts
  src/helpers/controlSize.ts
  src/index.tsx
  stories/graphs.stories.tsx
  stories/label.stories.tsx
  test/bargraph.test.tsx
  test/label.test.tsx
  test/layout.test.tsx
  test/videoplayer.test.tsx
Labels: bug

#139 feat(dashboard): adds dashboard icon
  src/components/Icon/Icon.tsx
  src/components/Icon/interfaces.ts
  stories/icons.stories.tsx
  test/icon.test.tsx
Labels: enhancement

#142 feat(breadcrumbs): adds breadcrumbs and child
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/BreadcrumbItem.tsx
  src/components/Breadcrumb/index.tsx
  src/index.tsx
  stories/breadcrumbs.stories.tsx
  stories/lists.stories.tsx
  test/breadcrumb.test.tsx
Labels: enhancement, in progress

#159 fix(datetimepicker): fix DateTimePicker style
  src/components/DateTimePicker/DateTimePicker.tsx
  stories/datetimepicker.stories.tsx
  test/datetimepicker.test.tsx
Labels: enhancement

#148 feat(navbar): adds customizable search and label color
  docs/Navbar.md
  docs/Navbar/Brand.md
  docs/Navbar/Navbar.md
  docs/Navbar/Search.md
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/interfaces.tsx
  stories/navbar.stories.tsx
  test/navbar.test.tsx
Labels: enhancement, in progress

#174 feat(calendar): add calendar component
  package.json
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/interfaces.ts
  stories/calendar.stories.tsx
  test/calendar.test.tsx
Labels: enhancement

#169 feat(checkbox): add className and style props
  src/components/Checkbox/Checkbox.tsx
  stories/checkbox.stories.tsx
  test/checkbox.test.tsx
Labels: enhancement

#141 feat(components): add Label isRequired property and other options
  docs/Label.md
  src/components/Label/Label.tsx
  stories/label.stories.tsx
  test/label.test.tsx
Labels: enhancement

#179 update navbar onClickHandlers to be optional, update dependencies
  .eslintrc.js
  package.json
  src/components/Navbar/interfaces.tsx
  test/modal.test.tsx
  test/navbar.test.tsx
Labels: bug, dependencies, enhancement
