Repository HospitalRun/components, pull requests merged in 2019-11, with the labels that each got.

#91 feat(image): add Image component
  src/components/Image/Image.tsx
  src/components/Image/index.tsx
  src/index.tsx
  stories/image.stories.tsx
  test/image.test.tsx
Labels: enhancement, in progress

#92 feat(list): add list component
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/List/index.tsx
  src/index.tsx
  stories/lists.stories.tsx
  test/list.test.tsx
  test/listitem.test.tsx
Labels: in progress

#117 fix(richtext.test): window.matchMedia is not a function
  __mocks__/matchMediaMock.js
  package.json
  src/components/Select/Select.tsx
Labels: bug, dependencies, in progress

#123 fix(navbar): fix typo in onSearchButtonClick function name
  src/components/Navbar/Navbar.tsx
  stories/navbar.stories.tsx
  test/linegraph.test.tsx
  test/navbar.test.tsx
Labels: bug

#125 Video Player
  package.json
  src/components/VideoPlayer/VideoPlayer.tsx
  src/components/VideoPlayer/index.tsx
  src/index.tsx
  stories/tsconfig.json
  stories/videoplayer.stories.tsx
  test/videoplayer.test.tsx
  types/videoplayer.d.ts
Labels: enhancement, in progress

#130 Layout components
  src/components/Layout/Column.tsx
  src/components/Layout/Container.tsx
  src/components/Layout/Row.tsx
  src/components/Layout/index.tsx
  src/index.tsx
  stories/layout.stories.css
  stories/layout.stories.tsx
  test/layout.test.tsx
Labels: enhancement, in progress
