Repository HospitalRun/components, pull requests merged in 2020-06, with the labels that each got.

#449 feat(calendar): add callbacks to navigation buttons
  package.json
  src/components/Calendar/Calendar.tsx
  stories/calendar.stories.tsx
  test/calendar.test.tsx
Labels: in progress

#451 feat(Typography): Introduction of the Typography component
  src/components/Typography/Typography.tsx
  src/components/Typography/index.tsx
  src/index.tsx
  stories/typography.stories.tsx
  test/typography.test.tsx
Labels: enhancement

#438 feat(datetimepicker): add support for multiple languages
  src/components/DateTimePicker/DateTimePicker.tsx
  src/components/Dropdown/Dropdown.tsx
  stories/datetimepicker.stories.tsx
Labels: in progress

#460 Fix Windows build on Node 14
  .github/workflows/ci.yml
  package.json
Labels: bug, in progress

#455 feat(table): update table
  src/components/Table/Table.tsx
  src/components/Table/helper.tsx
  src/components/Table/index.tsx
  src/components/Table/interfaces.ts
  stories/table.stories.tsx
  test/table.test.tsx
Labels: enhancement, in progress

#463 Nav link list mod
  src/components/Icon/Icon.tsx
  src/components/Icon/interfaces.ts
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/interfaces.tsx
  stories/icons.stories.tsx
  stories/navbar.stories.tsx
  test/navbar.test.tsx
Labels: in progress

#485 fix(select): fix type of onchange
  src/components/Select/Select.tsx
Labels: in progress
