Repository HospitalRun/components, pull requests merged in 2020-05, with the labels that each got.

#388 fix(ci): fix automatic release job
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: bug, core-team, devops, in progress

#392 feat(navbar): implement autocomplete support for Navbar search
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/interfaces.tsx
  stories/navbar.stories.tsx
Labels: enhancement

#424 feat(navbar): icon can be added to navbar with its name and size
  package.json
  src/components/Icon/Icon.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/interfaces.tsx
  src/index.tsx
  stories/icons.stories.tsx
  stories/navbar.stories.tsx
  test/icon.test.tsx
  test/navbar.test.tsx
Labels: enhancement

#446 feat(modal): styling with props
  src/components/Modal/Modal.tsx
Labels: in progress

#447 fix(datetimepicker): errors with styling
  src/components/DateTimePicker/DateTimePicker.tsx
  src/components/Modal/Modal.tsx
Labels: in progress
