Repository HospitalRun/components, pull requests merged in 2020-02, with the labels that each got.

#260 Fix/input props
  src/components/TextField/TextField.tsx
  src/components/TextInput/TextInput.tsx
  test/textfield.test.tsx
  test/textinput.test.tsx
Labels: bug

#261 fix(typeahead): add ability to set default value
  src/components/Typeahead/Typeahead.tsx
  stories/typeahead.stories.tsx
  test/typeahead.test.tsx
Labels: enhancement

#297 feat(toast): add prop to control position
  src/components/Toaster/index.tsx
  src/components/Toaster/interfaces.ts
  stories/toaster.stories.tsx
Labels: in progress
