Repository HospitalRun/components, pull requests merged in 2020-01, with the labels that each got.

#172 feat(panels): adds panel component
  buildDocs.sh
  genDocs.sh
  src/components/Alert/Alert.tsx
  src/components/Badge/Badge.tsx
  src/components/Button/Button.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/interfaces.ts
  src/components/List/ListItem.tsx
  src/components/Panel/Panel.tsx
  src/components/Panel/index.tsx
  src/components/Pill/Pill.tsx
  src/index.tsx
  src/interfaces/index.tsx
  stories/panel.stories.tsx
  test/icon.test.tsx
  test/panel.test.tsx
Labels: enhancement

#140 feat(panels): adds panel component
  package.json
  src/components/Panel/Panel.tsx
  src/components/Panel/index.tsx
  stories/panel.stories.css
  stories/panel.stories.tsx
  stories/panel.stories.tsx.rej
Labels: duplicate, in progress, invalid, question

#154 feat(dropdown): add dropdown component
  docs/Dropdown/Dropdown.md
  docs/Dropdown/Item.md
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.tsx
  src/components/Dropdown/interfaces.tsx
  src/helpers/ColorVariants.ts
  src/index.tsx
  stories/dropdown.stories.tsx
  test/dropdown.test.tsx
Labels: enhancement

#168 feat(components): add className and style props
  src/components/Alert/Alert.tsx
  src/components/Badge/Badge.tsx
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/BreadcrumbItem.tsx
  src/components/Button/Button.tsx
  src/components/Icon/Icon.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Column.tsx
  src/components/Layout/Container.tsx
  src/components/Layout/Row.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Pill/Pill.tsx
  src/components/Radio/Radio.tsx
  src/components/Select/Select.tsx
  src/components/Switch/Switch.tsx
  src/components/TextField/TextField.tsx
  src/components/TextInput/TextInput.tsx
  stories/CustomClasses.css
  stories/alerts.stories.tsx
  stories/badges.stories.tsx
  stories/breadcrumbs.stories.tsx
  stories/buttons.stories.tsx
  stories/icons.stories.tsx
  stories/label.stories.tsx
  stories/layout.stories.tsx
  stories/lists.stories.tsx
  stories/pills.stories.tsx
  stories/radio.stories.tsx
  stories/select.stories.tsx
  stories/switch.stories.tsx
  stories/textfield.stories.tsx
  stories/textinput.stories.tsx
  stories/welcome.tsx
  test/alert.test.tsx
  test/badge.test.tsx
  test/breadcrumb.test.tsx
  test/button.test.tsx
  test/icon.test.tsx
  test/label.test.tsx
  test/layout.test.tsx
  test/list.test.tsx
  test/listitem.test.tsx
  test/pill.test.tsx
  test/radio.test.tsx
  test/select.test.tsx
  test/switch.test.tsx
  test/textfield.test.tsx
  test/textinput.test.tsx
Labels: enhancement, in progress

#190 fix(typings): adds @types/node package set to version 12 of node
  package.json
Labels: in progress

#184 fix(collapsible panel): adds pointer when cursor is hovered over icon
  src/components/Label/Label.tsx
  src/components/Panel/Panel.tsx
Labels: enhancement, in progress

#201 feat(css): create a Theme to override Bootstrap colors
  .eslintignore
  .storybook/webpack.config.js
  package.json
  scss/_variables.scss
  scss/main.scss
  src/components/Toaster/index.tsx
  src/components/Toaster/toaster.scss
  src/index.tsx
  stories/textfield.stories.tsx
  stories/toaster.stories.tsx
  tsdx.config.js
Labels: enhancement, in progress

#204 feat(typeahead): add typeahead component
  package.json
  src/components/Typeahead/Typeahead.tsx
  src/components/Typeahead/index.tsx
  src/index.tsx
  test/typeahead.test.tsx
Labels: enhancement, in progress

#193 feat(tab): add Tab and TabsHeader components
  src/components/Button/Button.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/interfaces.tsx
  src/components/Tab/Tab.tsx
  src/components/Tab/TabsHeader.tsx
  src/components/Tab/index.tsx
  src/helpers/ColorVariants.ts
  src/index.tsx
  src/interfaces/index.tsx
  stories/tab.stories.tsx
  test/button.test.tsx
  test/tab.test.tsx
Labels: enhancement, in progress

#221 fix(calendar): fix export for calendar
  src/index.tsx
  src/react-app-env.d.ts
  stories/calendar.stories.tsx
  test/calendar.test.tsx
Labels: bug

#236 fix(typeahead): add some missing props to typeahead component
  src/components/Typeahead/Typeahead.tsx
  stories/typeahead.stories.tsx
  test/typeahead.test.tsx
Labels: enhancement

#239 fix(textinput): add password, search, tel, url input types
  src/components/TextField/TextField.tsx
  src/components/TextInput/TextInput.tsx
  stories/textinput.stories.tsx
Labels: enhancement, in progress

#233 fix(panel): make panel collapse on header click
  src/components/Panel/Panel.tsx
  stories/panel.stories.tsx
  test/panel.test.tsx
Labels: enhancement

#228 feat(navbar): refactor navbar to support horizontal nav item placement and more
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/interfaces.tsx
  stories/navbar.stories.tsx
  test/navbar.test.tsx
Labels: enhancement
