Repository HospitalRun/components, pull requests merged in 2020-03, with the labels that each got.

#306 test(toaster): adds missing toaster tests
  test/alert.test.tsx
  test/bargraph.test.tsx
  test/linegraph.test.tsx
  test/modal.test.tsx
  test/navbar.test.tsx
  test/panel.test.tsx
  test/richtext.test.tsx
  test/spinner.test.tsx
  test/textfield.test.tsx
  test/textinput.test.tsx
  test/toaster.test.tsx
  test/typeahead.test.tsx
Labels: core-team, in progress

#268 feat: table
  .eslintrc.js
  package.json
  src/components/Table/Table.tsx
  src/components/Table/helper.tsx
  src/components/Table/index.tsx
  src/components/Table/interfaces.ts
  src/index.tsx
  stories/table.stories.tsx
  test/table.test.tsx
  types/react-table-config.d.ts
Labels: core-team, enhancement, in progress

#323 feat(input): adds validation feedback
  .vscode/settings.json
  package.json
  src/components/DateTimePicker/DateTimePicker.css
  src/components/DateTimePicker/DateTimePicker.tsx
  src/components/Radio/Radio.tsx
  src/components/Select/Select.tsx
  src/components/TextField/TextField.tsx
  src/components/TextInput/TextInput.tsx
  src/interfaces/index.tsx
  stories/CustomClasses.css
  stories/datetimepicker.stories.tsx
  stories/lists.stories.tsx
  stories/radio.stories.tsx
  stories/select.stories.tsx
  stories/textfield.stories.tsx
  stories/textinput.stories.tsx
  stories/typeahead.stories.tsx
  test/radio.test.tsx
  test/select.test.tsx
  test/textinput.test.tsx
Labels: enhancement

#341 feat(typeahead): added isinvalid prop to typeahead
  src/components/Typeahead/Typeahead.tsx
  stories/typeahead.stories.tsx
  test/typeahead.test.tsx
Labels: enhancement
